## Welcome to Python Numpy Arrays

In this small notebook I will guide you through the basics of Numpy arrays and get you up to speed on how they work.

## The basics

Numpy arrays are a way to define matrices and tensors (higher dimension matrices say a 3 by 3 by 3 'matrix') in python.

They allow easier mathematical operations on them.

And define things like the matrix multiplication.

To use numpy you must import it. I.e. tell python that it should use numpy by using:

In [1]:
import numpy as np

The 'as' part allows you to create an alias for that module. I.e. you can use numpy now by simply calling 'np' instead of 'numpy'

In [2]:
# so you can now create a 2 by 3 matrix full of zeros like so:
matrix = np.zeros((2,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


You could have just as well called 'import numpy' without the 'as' and it would work but you'd have to write 'numpy' every time instead of writing 'np' which is shorter. As so:

In [3]:
import numpy
matrix = numpy.zeros((2,3)) # I use 'numpy' instead of 'np'
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]]


### Create Matrices
If you want to create a matrix the usual way of doing this is to first create a list of lists where each inner list represents a row in the matrix and call np.array on it:

In [4]:
#let's import numpy
import numpy as np
listoflists = [ [1, 2, 3], [3, 2, 1]] # first list inside of the list is the first row. The second one will be the second row
numpyarray = np.array(listoflists) #this will make my list of lists into a numpy array that works like a matrix
print(numpyarray)

[[1 2 3]
 [3 2 1]]


#### Exercise:
Try to make a 2 by 3 matrix with the following entries: 

0, 5, 6

7, 2, -1

Print the matrix you've created at the end, it should look as:

[[0 5 6]

 [7 2 -1]]

In [ ]:
#code in here.

#### Exercise:

Try to make a 3 by 3 matrix with only ones in the diagonal and zeros elsewhere.

1, 0, 0

0, 1, 0

0, 0, 1

In [ ]:
#create your matrix here.

### Zeros, ones, and identity

Now that we have covered how to create a basic matrix manually, let's see what the functions zeros, ones and identity do:

In [5]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


As you can see it creates a matrix full of zeros of shape 2 by 3.
What do you think the function ones will do? Try to guess first and then run the code below:

In [ ]:
print(np.ones((2,3)))

What about the identity matrix? There's a function to make those easily for a SQUARE matrix.

In [ ]:
np.identity(3) # creates the identity matrix for a square matrix of size 3 by 3. 
#run the code using the play button and you will see the output below (only in a Jupyter notebook - use print in a script)

### Exercise

1. Create a matrix full of zeros of shape 10 by 15. Do not do it manually, use numpy's zeros function.
2. Create a matrix full of ones of shape 5 by 8. Use numpy's ones function.
3. Create an identity matrix with size of 10 (10 by 10).

In [ ]:
#1

In [ ]:
#2

In [ ]:
#3

### Accessing an element of the matrix

How would you access an element i,j in the matrix?

You would use:

In [8]:
matrix = np.array([[1, 2, 3], [3, 2, 1]])
matrix[1, 2] #access the 2nd row and the 3rd element.

1

You can also change the value of that element:

In [9]:
print("Before")
print(matrix)
matrix[1, 2] = 5
print("After")
print(matrix)

[[1 2 3]
 [3 2 1]]
[[1 2 3]
 [3 2 5]]


### Exercise:

Access the first row, and second column element of matrix below:

In [ ]:
matrix = np.array([[1, 2, 3], [3, 2, 1]])
#access and print the first row, second column: Remember that we count from 0 in python.




### Iterating through the matrix.

Say you have the matrix now created and you wanted to iterate through it, going cell by cell. Imagine an excel sheet, where you want to visit each cell.
How would you do that? The easiest way would be to use a for loop.

In [ ]:
#Create a matrix called matrix that is 5 by 10 full of ones:
matrix = ? #your code here

Now I am going to iterate through your matrix which should be 5 rows and 10 columns and add 2 to each cell.

In [ ]:
for i in range(5):
    for j in range(10):
        matrix[i, j] = matrix[i, j] + 2

### Excercise:

Create a matrix again this time the identity matrix of size 15.

Add 2 to every item on the diagonal. How would you recognize an item on the diagonal?

In [ ]:
### write your code here.

Let's add complexity. What if we wanted to start with a matrix full of zeros. And make all the borders equal to one?

First, can you create a matrix with only zeroes of size 10 by 10?

In [ ]:
#create your matrix here

Now can you iterate through the matrix and making all the border elements equal to one? Try to do this without looking at the partial solution below.

In [ ]:
#your attempt.

In [3]:
#partial solution
import numpy as np
#partial solution:
matrix = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        if(i == 0): #if the row is the top row then do the following.
            matrix[i, j] = 1
print(matrix)

#if you looked at the solution modify the code above to make all the zeros, ones in the left, right, and bottom border.

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Quick reminder on functions:

Let's go over the functions real quick to make sure you are up to date.

A function is some code that allows you to run the same code multiple times without having to write it again.

In [5]:
def add(x):
    return x + 2

This defines a function called 'add' that takes a variable 'x' and adds 2 to it and returns the result. We can now use it multiple times:

In [7]:
x = add(5) # result will be 7
y = add(10) #result will be 12
z = add(105) #result will be 107
print(x)
print(y)
print(z)

7
12
107


### Exercice

Create a function call substract that substracts 7 from a given number.

In [10]:
# code here


In [ ]:
# run this to verify your function, make sure you run your cell first and that your function is called 'substract'
value = True
for i in range(100):
    value *= (substract(i) == i - 7)
if(value):
    print("Your function worked as expected for 0, to 99.")
else:
    print("Your function didn't substract 7 to every number as expected.")

### Exercise

Create a function that will substract 5 if the number is odd (use %) or add 2 if the number is even. See https://stackoverflow.com/a/13636743/6451669

In [ ]:
## create your function

### Exercise

Create a function that calculates the nth number of the [Fibonnaci sequence](https://en.wikipedia.org/wiki/Fibonacci_number#Definition).

HINT: Inside a given function f you can call the f function too. It's called a [Recursive Function](https://www.w3schools.com/python/gloss_python_function_recursion.asp#:~:text=Python%20also%20accepts%20function%20recursion,data%20to%20reach%20a%20result.)

In [ ]:
# code here:


In [13]:
#solution (try not to look first)
def fibonnaci(n):
    if(n == 0):
        return 0
    if(n == 1):
        return 1
    return fibonnaci(n-1) + fibonnaci(n-2)

In [15]:
fibonnaci(13)

233